# 线性回归

## 向前计算实现

In [1]:
import torch
import math
import numpy as np

In [2]:
x = torch.ones([2,2],requires_grad=True)

In [3]:
x

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [4]:
b = x.add(2)

In [5]:
b

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)

In [6]:
# y = 3 * b * b
y =3 * torch.pow(b,2)

In [7]:
y

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>)

In [8]:
# out = torch.mean(y)
out = y.mean()

In [9]:
out

tensor(27., grad_fn=<MeanBackward0>)

In [10]:
a = torch.randn((2,2))

In [11]:
a.requires_grad

False

In [12]:
# 可以通过属性值进行修改
a.requires_grad_(True)

tensor([[-0.6180,  1.7095],
        [ 0.4860,  0.4538]], requires_grad=True)

In [13]:
b = a*a

In [14]:
b

tensor([[0.3820, 2.9223],
        [0.2362, 0.2059]], grad_fn=<MulBackward0>)

In [15]:
with torch.no_grad():
    c = a*a
c.requires_grad

False

## 反向传播

In [16]:
# 反向传播计算出参数的梯度值 
out.backward(retain_graph=True)

In [17]:
# 得到相应的值
x.grad

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])

In [23]:
# 通过这里可以发现，咱们通过设置  retain_graph = True 得到的梯度值有一个累加的过程
out.backward(retain_graph=True)

In [24]:
x.grad

tensor([[13.5000, 13.5000],
        [13.5000, 13.5000]])

In [26]:
# 注意： data属性是得到里面的数值，如果与x均是指代数值的时候就是相同的引用
# 由于含有 requires_grad = True 因此，获得数据用data或者下面的方法
x.data

tensor([[1., 1.],
        [1., 1.]])

In [27]:
y.data

tensor([[27., 27.],
        [27., 27.]])

In [29]:
y.detach().numpy()

array([[27., 27.],
       [27., 27.]], dtype=float32)

In [30]:
x.detach().numpy()

array([[1., 1.],
       [1., 1.]], dtype=float32)

In [34]:
x = torch.tensor(np.arange(500))

In [35]:
torch.rand([])

tensor(0.9912)

In [37]:
torch.tensor([])

tensor([])

In [39]:
# np.random.randint(0,255,size=3)

array([227, 122, 175])

## 图像形状的变化

In [40]:
from torchvision.transforms import ToTensor

In [41]:
a = torch.tensor(np.arange(24).reshape(2,4,3))

In [42]:
a

tensor([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8],
         [ 9, 10, 11]],

        [[12, 13, 14],
         [15, 16, 17],
         [18, 19, 20],
         [21, 22, 23]]])

In [43]:
a.transpose(0,2).transpose(1,2)

tensor([[[ 0,  3,  6,  9],
         [12, 15, 18, 21]],

        [[ 1,  4,  7, 10],
         [13, 16, 19, 22]],

        [[ 2,  5,  8, 11],
         [14, 17, 20, 23]]])

In [44]:
a.permute(2,0,1)

tensor([[[ 0,  3,  6,  9],
         [12, 15, 18, 21]],

        [[ 1,  4,  7, 10],
         [13, 16, 19, 22]],

        [[ 2,  5,  8, 11],
         [14, 17, 20, 23]]])

In [46]:
ToTensor()(a.numpy())

tensor([[[ 0,  3,  6,  9],
         [12, 15, 18, 21]],

        [[ 1,  4,  7, 10],
         [13, 16, 19, 22]],

        [[ 2,  5,  8, 11],
         [14, 17, 20, 23]]])

In [51]:
# a.data.numpy()
c = torch.randint(low=0,high=100,size=(4,4))

### 以下均为测试代码

In [52]:
c

tensor([[ 0, 77, 85, 25],
        [14, 95,  5, 67],
        [15, 53,  0, 69],
        [41, 23, 12, 40]])

In [53]:
c.max(dim=0)

torch.return_types.max(
values=tensor([41, 95, 85, 69]),
indices=tensor([3, 1, 0, 2]))

In [57]:
c.max(dim=-1)

torch.return_types.max(
values=tensor([85, 95, 69, 41]),
indices=tensor([2, 1, 3, 0]))

In [58]:
test = torch.randn([3,4],requires_grad=True)

In [59]:
test

tensor([[-0.6077, -0.1215,  0.3903, -0.1663],
        [-0.8981,  0.0901, -0.5452,  0.2846],
        [-0.6492, -1.6031,  0.4414,  0.6057]], requires_grad=True)

In [61]:
test.data.numpy()

array([[-0.6076861 , -0.12152922,  0.39031664, -0.16627671],
       [-0.89808196,  0.09014608, -0.54519135,  0.28461492],
       [-0.64917505, -1.6031339 ,  0.4413921 ,  0.60569406]],
      dtype=float32)

In [62]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

In [63]:
test.to(device)

tensor([[-0.6077, -0.1215,  0.3903, -0.1663],
        [-0.8981,  0.0901, -0.5452,  0.2846],
        [-0.6492, -1.6031,  0.4414,  0.6057]], requires_grad=True)

In [65]:
test.device

device(type='cpu')

In [66]:
test

tensor([[-0.6077, -0.1215,  0.3903, -0.1663],
        [-0.8981,  0.0901, -0.5452,  0.2846],
        [-0.6492, -1.6031,  0.4414,  0.6057]], requires_grad=True)

In [67]:
test[:,0] = 1

In [68]:
test

tensor([[ 1.0000, -0.1215,  0.3903, -0.1663],
        [ 1.0000,  0.0901, -0.5452,  0.2846],
        [ 1.0000, -1.6031,  0.4414,  0.6057]], grad_fn=<CopySlices>)

In [69]:
test.data

tensor([[ 1.0000, -0.1215,  0.3903, -0.1663],
        [ 1.0000,  0.0901, -0.5452,  0.2846],
        [ 1.0000, -1.6031,  0.4414,  0.6057]])

In [71]:
test.detach()

tensor([[ 1.0000, -0.1215,  0.3903, -0.1663],
        [ 1.0000,  0.0901, -0.5452,  0.2846],
        [ 1.0000, -1.6031,  0.4414,  0.6057]])

In [72]:
test[:,1] = 1

In [73]:
test.detach()

tensor([[ 1.0000,  1.0000,  0.3903, -0.1663],
        [ 1.0000,  1.0000, -0.5452,  0.2846],
        [ 1.0000,  1.0000,  0.4414,  0.6057]])

In [74]:
test.data

tensor([[ 1.0000,  1.0000,  0.3903, -0.1663],
        [ 1.0000,  1.0000, -0.5452,  0.2846],
        [ 1.0000,  1.0000,  0.4414,  0.6057]])