# Pytorch 基本使用

## 张量的创建

### 从已有的数据中创建

In [14]:
import torch
import numpy as np

In [2]:
torch.tensor((1,2,3))

tensor([1, 2, 3])

In [4]:
a = torch.tensor(1)

In [8]:
a.item()

1

In [11]:
b = torch.tensor(((4,5,6),(2,3,4)))

In [13]:
# b.size()
b.shape

torch.Size([2, 3])

In [17]:
torch.tensor(np.array(range(12)).reshape(3,4))

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [20]:
torch.tensor([[[(2,3,4),(4,5,6)]]]).size()

torch.Size([1, 1, 2, 3])

In [21]:
torch.tensor([[(1,2,3),(4,5,6)]]).size()

torch.Size([1, 2, 3])

In [22]:
torch.tensor(np.ones([3,4]))

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]], dtype=torch.float64)

In [29]:
c = torch.tensor(np.arange(12).reshape([3,4]))

In [30]:
c.view([2,6])

tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]])

### 创建指定的张量

In [31]:
torch.ones([2,3])

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [32]:
torch.zeros([3,4])

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [34]:
torch.empty([2,3]).dtype

torch.float32

In [37]:
torch.ones([3,4]).size(1)

4

In [38]:
a = torch.empty([3,4])

In [39]:
torch.ones_like(a)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

### 创建随机的张量

In [40]:
torch.rand([2,3])   # 创建从[0,1)范围的数

tensor([[0.8673, 0.9537, 0.5952],
        [0.2568, 0.7015, 0.6759]])

In [41]:
torch.randn([3,4])  # 创建符合标准正太分布的数

tensor([[ 0.7375,  0.1443, -0.2710,  1.2969],
        [-0.3377, -1.0959,  0.9944, -0.1113],
        [ 0.9836, -1.5075, -0.4609, -0.7312]])

In [42]:
torch.randint(low=0,high=100,size=[3,4])

tensor([[79, 81, 63, 78],
        [27, 79, 32, 31],
        [12, 14, 34, 10]])

In [43]:
a = torch.tensor((1))

In [44]:
a.item()

1

In [45]:
b = torch.randn([3,4])

In [46]:
type(b)  # torch.Tensor  可以看出来创建的 张量b 为Tensor的一个对象

torch.Tensor

In [47]:
b.numpy()

array([[-0.900767  , -0.7780989 , -0.11065675, -1.81396   ],
       [-1.0762653 , -0.65632546,  2.3769398 ,  0.84768564],
       [-0.5845618 ,  1.5691382 ,  0.34609595, -1.3984004 ]],
      dtype=float32)

## 张量的属性和方法

In [48]:
type(b.numpy())

numpy.ndarray

In [52]:
b.data.dtype

torch.float32

In [53]:
type(b.data)

torch.Tensor

In [54]:
b.dim()

2

In [55]:
torch.tensor([[[[(4,5,6)]]]]).dim()

5

In [56]:
torch.tensor(np.arange(12).reshape(3,4)).view(4,3)

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])

In [62]:
# 张量数据类型的变化
torch.tensor([1,2,3]).long().int().float().double()

tensor([1., 2., 3.], dtype=torch.float64)

In [64]:
# 转置往往在对角线出变化
torch.tensor([[1,2],[3,4]]).t()

tensor([[1, 3],
        [2, 4]])

In [65]:
torch.tensor([[(1,2,3),(4,5,6),(7,8,9)]]).dim()

3

In [66]:
c = torch.tensor([[[(1,2,3),(4,5,6)],(7,8,9)]])

In [69]:
c.size()

torch.Size([1, 3, 3])

In [73]:
d = torch.tensor([([1,2],[3,4]),([5,6],[7,8])])

In [74]:
d.size()

torch.Size([2, 2, 2])

In [76]:
d.transpose(0,1)

tensor([[[1, 2],
         [5, 6]],

        [[3, 4],
         [7, 8]]])

In [78]:
# 张量的索引以及切片
d[1,1,1].item()

8

In [79]:
d[1]

tensor([[5, 6],
        [7, 8]])

In [80]:
d[1,:]

tensor([[5, 6],
        [7, 8]])

In [82]:
d[:,:,1]

tensor([[2, 4],
        [6, 8]])

In [83]:
d[-1,-1] = 10

In [84]:
d

tensor([[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [10, 10]]])

In [86]:
c = {10:10,20:10}

In [90]:
a = d.numpy()

In [91]:
a

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [10, 10]]])

In [92]:
c[a[-1,-1,-1]]

10

In [94]:
g = torch.tensor([[1,2,3],[4,5,6]])

In [97]:
g.max().item()

6

In [103]:
g.max(dim=-1)

torch.return_types.max(
values=tensor([3, 6]),
indices=tensor([2, 2]))

In [105]:
# 由以上的结果可以看出来，max()函数里面可以添加参数，将得到一个列表，里面反应相应位置的最大值以及最大值的位置

In [106]:
m = torch.tensor([(1,2,3),(4,5,6)])

In [109]:
m.dtype

torch.int64

In [110]:
m.long()

tensor([[1, 2, 3],
        [4, 5, 6]])

In [112]:
# type(m)
m.dtype

torch.int64

In [113]:
m.type(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [114]:
m.type(torch.long)

tensor([[1, 2, 3],
        [4, 5, 6]])

In [115]:
m.type(torch.half)

tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float16)

In [117]:
# 大写所创建出来的是一个对象
torch.LongTensor([1,2,3]).dtype

torch.int64

####  三种方式来指定咱们的张量的类型

In [118]:
a = torch.LongTensor([1,2,3])
a.type(torch.float32)
torch.tensor([[1,2,3],[4,5,6]],dtype=torch.long)
a.long().float().double()

tensor([[1, 2, 3],
        [4, 5, 6]])

In [119]:
a = torch.ones([3,4],dtype=torch.double)

In [120]:
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]], dtype=torch.float64)

In [122]:
a.new_empty(size=a.size())

tensor([[ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  3.5098e+64, -0.0000e+00, 2.6868e+154]],
       dtype=torch.float64)

In [123]:
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]], dtype=torch.float64)

In [126]:
b = torch.randn([3,4]).double()

In [127]:
a+b

tensor([[ 0.2795,  0.2974, -0.1443,  0.3477],
        [ 1.7005,  0.4493, -0.7400,  0.6018],
        [ 2.1822,  2.4292,  1.1886,  0.1480]], dtype=torch.float64)

In [128]:
torch.add(a,b)

tensor([[ 0.2795,  0.2974, -0.1443,  0.3477],
        [ 1.7005,  0.4493, -0.7400,  0.6018],
        [ 2.1822,  2.4292,  1.1886,  0.1480]], dtype=torch.float64)

In [129]:
a.add(b)

tensor([[ 0.2795,  0.2974, -0.1443,  0.3477],
        [ 1.7005,  0.4493, -0.7400,  0.6018],
        [ 2.1822,  2.4292,  1.1886,  0.1480]], dtype=torch.float64)

In [130]:
a.add_(b)

tensor([[ 0.2795,  0.2974, -0.1443,  0.3477],
        [ 1.7005,  0.4493, -0.7400,  0.6018],
        [ 2.1822,  2.4292,  1.1886,  0.1480]], dtype=torch.float64)

#### 注意：带下划线的方法（比如:add_)会对tensor进行就地修改

In [131]:
a

tensor([[ 0.2795,  0.2974, -0.1443,  0.3477],
        [ 1.7005,  0.4493, -0.7400,  0.6018],
        [ 2.1822,  2.4292,  1.1886,  0.1480]], dtype=torch.float64)

## CUDA类型的tensor

In [132]:
device = torch.device("cuda:0" if torch.cuda.is_available() else 'cpu')  # 0 表示第0块gpu

In [133]:
device

device(type='cpu')

In [134]:
a

tensor([[ 0.2795,  0.2974, -0.1443,  0.3477],
        [ 1.7005,  0.4493, -0.7400,  0.6018],
        [ 2.1822,  2.4292,  1.1886,  0.1480]], dtype=torch.float64)

In [135]:
a.device

device(type='cpu')

In [136]:
a = a.to(device)

In [138]:
a.device

device(type='cpu')

In [140]:
a.cpu().numpy()

array([[ 0.27945817,  0.29740566, -0.14431012,  0.34765291],
       [ 1.70051825,  0.44928783, -0.7399857 ,  0.60176182],
       [ 2.18215477,  2.42923677,  1.18855689,  0.14798063]])

In [ ]:
# 方法总结：
1.cuda转化为CPU  通过 .cpu() 的方法
2.转化为 GPU的方法： a.  tensor.to(device)  b. 创建的时候指定device 