# 线性回归

## 向前计算实现

In [1]:
import torch
import math
import numpy as np

In [2]:
x = torch.ones([2,2],requires_grad=True)

In [3]:
x

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [4]:
b = x.add(2)

In [5]:
b

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)

In [6]:
# y = 3 * b * b
y =3 * torch.pow(b,2)

In [7]:
y

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>)

In [8]:
# out = torch.mean(y)
out = y.mean()

In [9]:
out

tensor(27., grad_fn=<MeanBackward0>)

In [10]:
a = torch.randn((2,2))

In [11]:
a.requires_grad

False

In [12]:
# 可以通过属性值进行修改
a.requires_grad_(True)

tensor([[-0.6180,  1.7095],
        [ 0.4860,  0.4538]], requires_grad=True)

In [13]:
b = a*a

In [14]:
b

tensor([[0.3820, 2.9223],
        [0.2362, 0.2059]], grad_fn=<MulBackward0>)

In [15]:
with torch.no_grad():
    c = a*a
c.requires_grad

False

## 反向传播

In [16]:
# 反向传播计算出参数的梯度值 
out.backward(retain_graph=True)

In [17]:
# 得到相应的值
x.grad

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])

In [23]:
# 通过这里可以发现，咱们通过设置  retain_graph = True 得到的梯度值有一个累加的过程
out.backward(retain_graph=True)

In [24]:
x.grad

tensor([[13.5000, 13.5000],
        [13.5000, 13.5000]])

In [26]:
# 注意： data属性是得到里面的数值，如果与x均是指代数值的时候就是相同的引用
# 由于含有 requires_grad = True 因此，获得数据用data或者下面的方法
x.data

tensor([[1., 1.],
        [1., 1.]])

In [27]:
y.data

tensor([[27., 27.],
        [27., 27.]])

In [29]:
y.detach().numpy()

array([[27., 27.],
       [27., 27.]], dtype=float32)

In [30]:
x.detach().numpy()

array([[1., 1.],
       [1., 1.]], dtype=float32)